name: CI Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build-android:
    runs-on: macos-15
    name: Build
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
        
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
          
      - name: Restore Dependencies
        run: dotnet restore Softhand.sln

      - name: Build MAUI Android
        run: |
          dotnet build Softhand.sln -c Release -v diag --no-restore
        env:
          OUTPUT_DIR: ${{ github.workspace }}/publish

      # - name: Upload Android Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: softhand
      #     path: ${{ env.OUTPUT_DIR }}/*Signed.a*
      #   env:
      #     OUTPUT_DIR: ${{ github.workspace }}/publish
