name: CI Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  build-android:
    runs-on: macos-15
    name: Android Build
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
        
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
          
      - name: Restore Dependencies
        run: dotnet restore src/Softhand/Softhand.csproj

      - name: Build MAUI Android
        run: |
          cd ${{ github.workspace }}/src/Softhand/
          dotnet publish -c Release -f net9.0-android -o ${{ env.OUTPUT_DIR }}--no-restore
        env:
          OUTPUT_DIR: ${{ github.workspace }}/publish

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: softhand-android-ci-build
          path: ${{ env.OUTPUT_DIR }}/*Signed.a*
        env:
          OUTPUT_DIR: ${{ github.workspace }}/publish
# MAUI iOS Build
  build-ios:
    runs-on: macos-15
    name: iOS Build
    steps:

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
        
      - name: Restore Dependencies
        run: |
          cd ${{ github.workspace }}/src/Softhand/
          dotnet restore Softhand.csproj

      - name: Build MAUI iOS
        run: |
          cd ${{ github.workspace }}/src/Softhand/
          dotnet build -c Release -f net9.0-ios -r iossimulator-arm64 -o ${{ env.OUTPUT_DIR }}/publish --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False
        env:
          OUTPUT_DIR: ${{ github.workspace }}/publish

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: softhand-iossimulator-ci-build
          path: ${{ env.OUTPUT_DIR }}/*.app
        env:
          OUTPUT_DIR: ${{ github.workspace }}/publish