name: Extract Version

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  extract-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract version from .csproj
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" ${{ github.workspace }}/src/Softhand/Softhand.csproj)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate version badge SVG
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='120' height='20'> <rect width='120' height='20' fill='#00FFFF'/> <text x='10' y='14' font-family='Verdana' font-size='12' fill='#000'>version: $VERSION</text></svg>" > version-badge.svg

      - name: Move badge to repo folder
        run: |
          mkdir -p badges
          mv version-badge.svg badges/version.svg

      - name: Commit badge to repo
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update version badge to ${{ steps.get_version.outputs.version }}"
          add: "badges/version.svg"
