name: Extract Version

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  extract-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract version from .csproj
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" ${{ github.workspace }}/src/Softhand/Softhand.csproj)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: Create version badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GITHUB_TOKEN }}
          label: version
          message: ${{ steps.get_version.outputs.version }}
          color: blue
